In [1]:
import cv2
import imutils




In [2]:
image=cv2.imread("C:/Users/Asus/Downloads/opencv-tutorial/opencv-tutorial/tetris_blocks.png")

In [3]:
cv2.imshow("tetris",image)
cv2.waitKey(0)


106

In [3]:
(h,w,d)=image.shape

In [4]:
h,w,d

(250, 482, 3)

In [4]:
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

In [12]:
cv2.imshow("gray",gray)
cv2.waitKey(0)
cv2.destroyWindow("gray")

In [9]:
import numpy as np

In [10]:
image

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

# A low level implementation of canny edge detection

In [11]:
image

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [15]:
import numpy as np
import imutils
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

In [17]:
gray

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [18]:
filte=np.asarray([[1,1,1],[1,1,1],[1,1,1]])

In [19]:
filtediv=filte/9

In [20]:
type(filte)

numpy.ndarray

In [21]:
filte.shape

(3, 3)

In [22]:
import scipy

In [23]:
from scipy.ndimage import convolve

In [24]:
from scipy import signal

In [25]:
conv=signal.convolve2d(gray,filte,"same")

In [26]:
gray.shape

(250, 482)

In [27]:
conv

array([[1020, 1530, 1530, ..., 1530, 1530, 1020],
       [1530, 2295, 2295, ..., 2295, 2295, 1530],
       [1530, 2295, 2295, ..., 2295, 2295, 1530],
       ...,
       [1530, 2295, 2295, ..., 2295, 2295, 1530],
       [1530, 2295, 2295, ..., 2295, 2295, 1530],
       [1020, 1530, 1530, ..., 1530, 1530, 1020]])

In [28]:
max=np.max(conv)

In [29]:
max

2295

In [30]:
normalize=2295//255


In [31]:
normalize

9

In [32]:
convnormal=conv//9

In [33]:
convnormal=convnormal.astype("uint8")

In [34]:
convnormal

array([[113, 170, 170, ..., 170, 170, 113],
       [170, 255, 255, ..., 255, 255, 170],
       [170, 255, 255, ..., 255, 255, 170],
       ...,
       [170, 255, 255, ..., 255, 255, 170],
       [170, 255, 255, ..., 255, 255, 170],
       [113, 170, 170, ..., 170, 170, 113]], dtype=uint8)

In [35]:
np.max(convnormal)

255

In [36]:
cv2.imshow("blurred",convnormal)
cv2.waitKey(0)

13

In [37]:
sobelv=np.asarray([[-1,0,1],[-2,0,2],[-1,0,1]])

In [38]:
sobelv

array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

In [39]:
sobelh=sobelv.T

In [40]:
sobelh

array([[-1, -2, -1],
       [ 0,  0,  0],
       [ 1,  2,  1]])

In [41]:
edgeh=signal.convolve2d(convnormal,sobelh,"same")

In [42]:
edgeh

array([[ -595,  -935, -1020, ..., -1020,  -935,  -595],
       [ -199,  -312,  -340, ...,  -340,  -312,  -199],
       [    0,     0,     0, ...,     0,     0,     0],
       ...,
       [    0,     0,     0, ...,     0,     0,     0],
       [  199,   312,   340, ...,   340,   312,   199],
       [  595,   935,  1020, ...,  1020,   935,   595]])

In [43]:
np.max(np.abs(edgeh))

1020

In [44]:
normal2=1020//255

In [45]:
normal2

4

In [46]:
edgeh=edgeh/4

In [47]:
edgeh=edgeh.astype("float32")

In [48]:
cv2.imshow("horiz",edgeh)
cv2.waitKey(0)

13

In [49]:
edgev=signal.convolve2d(convnormal,sobelv,"same")

In [50]:
edgev=edgev//4

In [51]:
edgev=edgev.astype("float32")

In [52]:
edgev

array([[-149.,  -50.,    0., ...,    0.,   49.,  148.],
       [-234.,  -78.,    0., ...,    0.,   78.,  233.],
       [-255.,  -85.,    0., ...,    0.,   85.,  255.],
       ...,
       [-255.,  -85.,    0., ...,    0.,   85.,  255.],
       [-234.,  -78.,    0., ...,    0.,   78.,  233.],
       [-149.,  -50.,    0., ...,    0.,   49.,  148.]], dtype=float32)

In [53]:
cv2.imshow("verti",edgev)
cv2.waitKey(0)

107

In [54]:
edge=(edgeh**2+edgev**2)

In [55]:
edge

array([[44327.562, 57139.062, 65025.   , ..., 65025.   , 57040.062,
        44030.562],
       [57231.062, 12168.   ,  7225.   , ...,  7225.   , 12168.   ,
        56764.062],
       [65025.   ,  7225.   ,     0.   , ...,     0.   ,  7225.   ,
        65025.   ],
       ...,
       [65025.   ,  7225.   ,     0.   , ...,     0.   ,  7225.   ,
        65025.   ],
       [57231.062, 12168.   ,  7225.   , ...,  7225.   , 12168.   ,
        56764.062],
       [44327.562, 57139.062, 65025.   , ..., 65025.   , 57040.062,
        44030.562]], dtype=float32)

In [56]:
final=pow(edge,0.5)

In [57]:
final

array([[210.54112 , 239.03778 , 255.      , ..., 255.      , 238.83061 ,
        209.83461 ],
       [239.23015 , 110.308655,  85.      , ...,  85.      , 110.308655,
        238.2521  ],
       [255.      ,  85.      ,   0.      , ...,   0.      ,  85.      ,
        255.      ],
       ...,
       [255.      ,  85.      ,   0.      , ...,   0.      ,  85.      ,
        255.      ],
       [239.23015 , 110.308655,  85.      , ...,  85.      , 110.308655,
        238.2521  ],
       [210.54112 , 239.03778 , 255.      , ..., 255.      , 238.83061 ,
        209.83461 ]], dtype=float32)

In [58]:
type(final)

numpy.ndarray

In [59]:
final=final.astype("float32")

In [60]:
cv2.imshow("edges",final)
cv2.waitKey(0)

109

In [61]:
edged = cv2.Canny(gray, 30, 150)
cv2.imshow("Edged", edged)
cv2.waitKey(0)

109

In [62]:
def non_max_suppression(img, D):
    M, N = img.shape
    Z = np.zeros((M,N), dtype=np.int32)
    angle = D * 180. / np.pi
    angle[angle < 0] += 180

    
    for i in range(1,M-1):
        for j in range(1,N-1):
            try:
                q = 255
                r = 255
                
               #angle 0
                if (0 <= angle[i,j] < 22.5) or (157.5 <= angle[i,j] <= 180):
                    q = img[i, j+1]
                    r = img[i, j-1]
                #angle 45
                elif (22.5 <= angle[i,j] < 67.5):
                    q = img[i+1, j-1]
                    r = img[i-1, j+1]
                #angle 90
                elif (67.5 <= angle[i,j] < 112.5):
                    q = img[i+1, j]
                    r = img[i-1, j]
                #angle 135
                elif (112.5 <= angle[i,j] < 157.5):
                    q = img[i-1, j-1]
                    r = img[i+1, j+1]

                if (img[i,j] >= q) and (img[i,j] >= r):
                    Z[i,j] = img[i,j]
                else:
                    Z[i,j] = 0

            except IndexError as e:
                pass
    
    return Z


In [63]:
m,n=edge.shape

In [64]:
d = np.zeros((m,n), dtype=np.float32)

In [65]:
import math

In [66]:
for i in range(0,m):
    for j in range(0,n):
        if(edgeh[i,j]!=0):
            d[i,j]=math.atan(edgev[i,j]/edgeh[i,j])
        else:
            d[i,j]=1.5708
        

In [67]:
d

array([[ 0.78623784,  0.2107281 , -0.        , ..., -0.        ,
        -0.20663364, -0.78287077],
       [ 1.3613087 ,  0.7853982 , -0.        , ..., -0.        ,
        -0.7853982 , -1.3604358 ],
       [ 1.5708    ,  1.5708    ,  1.5708    , ...,  1.5708    ,
         1.5708    ,  1.5708    ],
       ...,
       [ 1.5708    ,  1.5708    ,  1.5708    , ...,  1.5708    ,
         1.5708    ,  1.5708    ],
       [-1.3613087 , -0.7853982 ,  0.        , ...,  0.        ,
         0.7853982 ,  1.3604358 ],
       [-0.78623784, -0.2107281 ,  0.        , ...,  0.        ,
         0.20663364,  0.78287077]], dtype=float32)

In [68]:
d.shape

(250, 482)

In [69]:
z=non_max_suppression(edge,d)

In [70]:
z

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [71]:
z.shape

(250, 482)

In [72]:
nor=np.max(z)/255

In [73]:
nor

93.00392156862745

In [74]:
z=z//nor

In [75]:
z=z.astype("float32")

In [76]:
cv2.imshow("res",z)
cv2.waitKey(0)

109

In [77]:
np.max(z)

255.0

In [78]:
z2=non_max_suppression(z,d)

In [79]:
nor2=np.max(z2)/255

In [80]:
nor2

1.0

In [81]:
z=z//nor2

In [82]:
z2=z2.astype("float32")

In [85]:
cv2.imshow("res2",z2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
thresh = cv2.threshold(gray, 225, 255, cv2.THRESH_BINARY_INV)[1]
cv2.imshow("Thresh", thresh)
cv2.waitKey(0)

107

In [6]:
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,
cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
output = image.copy()


In [7]:
for c in cnts:
    cv2.drawContours(output, [c], -1, (240, 0, 159), 3)
cv2.imshow("Contours", output)
cv2.waitKey(0) 
    
    


109

In [8]:
text = "I found {} objects!".format(len(cnts))
cv2.putText(output, text, (10, 25),  cv2.FONT_HERSHEY_SIMPLEX, 0.7,
(240, 0, 159), 2)
cv2.imshow("Contours", output)
cv2.waitKey(0)

110

In [13]:
mask=thresh.copy()
erode=cv2.erode(mask,None,iterations=5)
cv2.imshow("eroded",erode)
cv2.waitKey(0)

106

In [14]:
dilate=cv2.dilate(mask,None,iterations=5)
cv2.imshow("dilated",dilate)
cv2.waitKey(0)

110

In [15]:
mask = thresh.copy()
output = cv2.bitwise_and(image, image, mask=mask)
cv2.imshow("Output", output)
cv2.waitKey(0)

109