In [132]:
import cv2
import numpy as np

In [133]:
sudoku=cv2.imread("D:/Udemy/original/Master OpenCV/images/soduku.jpg")

In [134]:
gray=cv2.cvtColor(sudoku,cv2.COLOR_BGR2GRAY)

In [135]:
cv2.imshow("sudoku",sudoku)
cv2.waitKey(0)

107

In [137]:
sudoku

array([[[ 5, 22, 25],
        [ 7, 24, 27],
        [ 6, 23, 26],
        ...,
        [ 1,  3,  4],
        [ 1,  0,  2],
        [29, 26, 28]],

       [[ 7, 24, 27],
        [ 8, 25, 28],
        [ 7, 24, 27],
        ...,
        [ 0,  2,  3],
        [ 0,  0,  1],
        [11, 10, 12]],

       [[ 8, 25, 28],
        [ 8, 25, 28],
        [ 9, 26, 29],
        ...,
        [ 0,  2,  3],
        [ 0,  1,  2],
        [ 0,  1,  2]],

       ...,

       [[16, 34, 35],
        [17, 35, 36],
        [15, 33, 34],
        ...,
        [32, 47, 33],
        [32, 47, 33],
        [32, 47, 33]],

       [[15, 33, 34],
        [16, 34, 35],
        [14, 32, 33],
        ...,
        [31, 46, 32],
        [31, 45, 33],
        [32, 46, 34]],

       [[13, 31, 32],
        [15, 33, 34],
        [16, 34, 35],
        ...,
        [30, 45, 31],
        [30, 44, 32],
        [32, 46, 34]]], dtype=uint8)

In [138]:
edged=cv2.Canny(gray,100,170,apertureSize=3)

In [139]:
gray.shape

(576, 768)

In [140]:
lines=cv2.HoughLines(edged,1,np.pi/180,240)

In [141]:
lines

array([[[   4.       ,    2.8797932]],

       [[   2.       ,    2.8797932]],

       [[ 637.       ,    1.2566371]],

       [[ -77.       ,    2.8274333]],

       [[ 507.       ,    1.2740903]],

       [[-476.       ,    2.6179938]],

       [[ 505.       ,    1.2740903]],

       [[-130.       ,    2.7925267]],

       [[ 379.       ,    1.2915436]],

       [[ 323.       ,    1.2915436]],

       [[ -21.       ,    2.86234  ]],

       [[ 634.       ,    1.2566371]],

       [[ -24.       ,    2.86234  ]],

       [[ 574.       ,    1.2566371]],

       [[-387.       ,    2.6703537]],

       [[  21.       ,    2.8797932]],

       [[-284.       ,    2.7052603]],

       [[-429.       ,    2.6354473]],

       [[ -75.       ,    2.8274333]],

       [[-128.       ,    2.7925267]],

       [[ 381.       ,    1.2915436]],

       [[-485.       ,    2.6354473]],

       [[-282.       ,    2.7052603]],

       [[ 121.       ,    1.3089969]],

       [[ 384.       ,    1.2740903]],



In [142]:
lines.shape

(34, 1, 2)

In [143]:
lines[0].shape

(1, 2)

In [144]:
lines[0][0].shape

(2,)

In [145]:
lines[0]

array([[4.       , 2.8797932]], dtype=float32)

In [146]:
for line in lines:
    rho,theta=line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(sudoku,(x1,y1),(x2,y2),(0,0,255),2)

cv2.imwrite('houghlines3.jpg',sudoku)

True

In [147]:
cv2.imshow("hough",sudoku)
cv2.waitKey(0)

106

In [32]:
cv2.imshow("edged",edged)
cv2.waitKey(0)

109

In [148]:
cv2.destroyAllWindows()